# =================================================================================
# KashViT: SVTR (Vision Transformer) Configuration for Kashmiri OCR
# =================================================================================

Global:
  debug: false
  use_gpu: true
  epoch_num: 100
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./model_checkpoints/
  save_epoch_step: 5
  
  # Evaluate on the validation set at the start (step 0) and every 500 steps thereafter.
  eval_batch_step: [0, 500] 
  cal_metric_during_train: true
  
  # No pretrained model for now, we will train from scratch.
  pretrained_model: null 
  checkpoints: null
  
  # Paths for our dataset
  character_dict_path: ./dict/koashurkhat_dict.txt
  max_text_length: &max_text_length 50
  use_space_char: true

# =================================================================================
# Optimizer and Learning Rate
# =================================================================================

Optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.99
  epsilon: 1.0e-08
  weight_decay: 0.05
  lr:
    name: Cosine
    learning_rate: 0.0005
    warmup_epoch: 2

# =================================================================================
# Model Architecture: SVTR (Small Vision Transformer)
# =================================================================================

Architecture:
  model_type: rec
  algorithm: SVTR
  Transform: null
  Backbone:
    name: SVTRNet
    img_size: [32, 320]
    out_channels: 192
    patch_merging: 'Conv'
    embed_dim: [64, 128, 256]
    depth: [3, 6, 3]
    num_heads: [2, 4, 8]
    mixer: ['Local','Local','Local','Local','Local','Local','Global','Global','Global','Global','Global','Global']
    local_mixer: [[7, 11], [7, 11], [7, 11]]
    last_stage: true
  Head:
    name: CTCHead
    fc_decay: 0.00001

# =================================================================================
# Loss, Post-Processing, and Metrics
# =================================================================================

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

# =================================================================================
# Datasets (Train and Validation)
# =================================================================================

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./
    label_file_list: ["./dataset/train.txt"]
    transforms:
      - DecodeImage: {img_mode: BGR, channel_first: false}
      - RecAug:
      - CTCLabelEncode:
      - RecResizeImg: {image_shape: [3, 32, 320]}
      - KeepKeys: {keep_keys: ['image', 'label', 'length']}
  loader:
    shuffle: true
    batch_size_per_card: 64 # Adjust based on your GPU memory
    drop_last: true
    num_workers: 4 # Adjust based on your system's cores

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./
    label_file_list: ["./dataset/val.txt"]
    transforms:
      - DecodeImage: {img_mode: BGR, channel_first: false}
      - CTCLabelEncode:
      - RecResizeImg: {image_shape: [3, 32, 320]}
      - KeepKeys: {keep_keys: ['image', 'label', 'length']}
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 64 # Adjust based on your GPU memory
    num_workers: 4
